<a href="https://colab.research.google.com/github/TinkerTechie/NeuralNetwork/blob/main/lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import numpy as np

In [52]:
df1 = pd.read_csv("indian_engineering_student_placement.csv")

In [53]:
df1.head()

,Student_ID,gender,branch,cgpa,tenth_percentage,twelfth_percentage,backlogs,study_hours_per_day,attendance_percentage,projects_completed,...,aptitude_skill_rating,hackathons_participated,certifications_count,sleep_hours,stress_level,part_time_job,family_income_level,city_tier,internet_access,extracurricular_involvement
0,1,Male,ECE,8.74,74.0,75.0,0,3.8,71.1,7,...,5,4,5,6.5,8,Yes,Medium,Tier 2,Yes,Medium
1,2,Female,ECE,7.80,75.3,69.7,0,6.3,69.5,5,...,3,4,1,7.1,8,Yes,Medium,Tier 3,Yes,Low
2,3,Female,IT,6.95,62.8,68.3,0,1.5,62.5,8,...,4,6,3,6.1,2,No,Low,Tier 2,Yes,High
3,4,Male,ECE,7.46,57.9,51.4,1,4.7,64.6,6,...,4,2,2,7.3,7,No,Medium,Tier 1,Yes,Low
4,5,Male,IT,6.86,61.3,73.5,2,5.2,75.9,3,...,3,2,1,6.0,7,No,Medium,Tier 1,Yes,Medium

In [54]:
df2 = pd.read_csv("placement_targets.csv")

In [55]:
df2.head()

   Student_ID placement_status  salary_lpa
0           1           Placed       14.95
1           2           Placed       14.91
2           3           Placed       17.73
3           4           Placed       14.52
4           5           Placed       15.91

In [56]:
df = pd.merge(df1,df2)

In [57]:
df.head()

,Student_ID,gender,branch,cgpa,tenth_percentage,twelfth_percentage,backlogs,study_hours_per_day,attendance_percentage,projects_completed,...,certifications_count,sleep_hours,stress_level,part_time_job,family_income_level,city_tier,internet_access,extracurricular_involvement,placement_status,salary_lpa
0,1,Male,ECE,8.74,74.0,75.0,0,3.8,71.1,7,...,5,6.5,8,Yes,Medium,Tier 2,Yes,Medium,Placed,14.95
1,2,Female,ECE,7.80,75.3,69.7,0,6.3,69.5,5,...,1,7.1,8,Yes,Medium,Tier 3,Yes,Low,Placed,14.91
2,3,Female,IT,6.95,62.8,68.3,0,1.5,62.5,8,...,3,6.1,2,No,Low,Tier 2,Yes,High,Placed,17.73
3,4,Male,ECE,7.46,57.9,51.4,1,4.7,64.6,6,...,2,7.3,7,No,Medium,Tier 1,Yes,Low,Placed,14.52
4,5,Male,IT,6.86,61.3,73.5,2,5.2,75.9,3,...,1,6.0,7,No,Medium,Tier 1,Yes,Medium,Placed,15.91

In [58]:
df.select_dtypes(include='object').columns

Index(['gender', 'branch', 'part_time_job', 'family_income_level', 'city_tier',
       'internet_access', 'extracurricular_involvement', 'placement_status'],
      dtype='object')

In [59]:
df['extracurricular_involvement'] = df['extracurricular_involvement'].fillna(df['extracurricular_involvement'].mode()[0])

In [60]:
df.isna().sum()

Student_ID                     0
gender                         0
branch                         0
cgpa                           0
tenth_percentage               0
twelfth_percentage             0
backlogs                       0
study_hours_per_day            0
attendance_percentage          0
projects_completed             0
internships_completed          0
coding_skill_rating            0
communication_skill_rating     0
aptitude_skill_rating          0
hackathons_participated        0
certifications_count           0
sleep_hours                    0
stress_level                   0
part_time_job                  0
family_income_level            0
city_tier                      0
internet_access                0
extracurricular_involvement    0
placement_status               0
salary_lpa                     0
dtype: int64

In [61]:
df.select_dtypes(include='object').columns

Index(['gender', 'branch', 'part_time_job', 'family_income_level', 'city_tier',
       'internet_access', 'extracurricular_involvement', 'placement_status'],
      dtype='object')

In [62]:
categorical_cols = [
    'gender',
    'branch',
    'part_time_job',
    'family_income_level',
    'city_tier',
    'internet_access',
    'extracurricular_involvement'
]

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [63]:
X = df.drop(['placement_status', 'Student_ID'], axis=1)
y = df['placement_status'].map({'Not Placed': 0, 'Placed': 1})

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [65]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [66]:
model = Sequential()

model.add(Dense(16, activation='relu', input_shape=(X_train.shape[1],)))


model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [67]:
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [68]:
history = model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=16,
    validation_data=(X_test, y_test)
)

Epoch 1/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8807 - loss: 0.3185 - val_accuracy: 0.9900 - val_loss: 0.0307
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9958 - loss: 0.0177 - val_accuracy: 1.0000 - val_loss: 0.0088
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9997 - loss: 0.0075 - val_accuracy: 1.0000 - val_loss: 0.0044
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9996 - loss: 0.0047 - val_accuracy: 1.0000 - val_loss: 0.0026
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9998 - loss: 0.0021 - val_accuracy: 1.0000 - val_loss: 0.0017
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 1.0000 - val_loss: 0.0017
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9998 - loss: 0.0018 - val_accuracy: 1.0000 - val_loss: 8.0440e-04
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 7.9650e-04 - val_accuracy: 1.0000 - val_loss: 6.1108e-04
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 9.0807e-04 - val_accuracy: 1.0000 - val_loss: 5.0947e-04
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9999 - loss: 5.9156e-04 - val_accuracy: 1.0000 - val_loss: 4.2444e-04
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 4.6677e-04 - val_accuracy: 1.0000 - val_loss: 3.8812e-04
Epoch 12/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 6.3198e-04 - val_accuracy: 1.0000 - val_loss: 2.4784e-04
Epoch 13/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 3.0882e-04 - val_accuracy: 1.0000 - val_loss: 2.4660e-04
Epoch 14/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 3.8224e-04 - val_accuracy: 1.0000 - val_loss: 2.0535e-04
Epoch 15/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 2.3500e-04 - val_accuracy: 1.0000 - val_loss: 1.8471e-04
Epoch 16/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 1.0907e-04 - val_accuracy: 1.0000 - val_loss: 2.0387e-04
Epoch 17/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 1.9885e-04 - val_accuracy: 1.0000 - val_loss: 1.0434e-04
Epoch 18/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 9.7172e-05 - val_accuracy: 1.0000 - val_loss: 8.9307e-05
Epoch 19/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 1.0768e-04 - val_accuracy: 1.0000 - val_loss: 8.2518e-05
Epoch 20/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 5.6164e-05 - val_accuracy: 1.0000 - val_loss: 6.5215e-05
Epoch 21/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 1.0000 - loss: 7.8766e-05 - val_accuracy: 1.0000 - val_loss: 5.6067e-05
Epoch 22/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 1.0000 - loss: 6.4812e-05 - val_accuracy: 1.0000 - val_loss: 5.0604e-05
Epoch 23/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 4.5927e-05 - val_accuracy: 1.0000 - val_loss: 4.2864e-05
Epoch 24/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 5.8884e-05 - val_accuracy: 1.0000 - val_loss: 4.6057e-05
Epoch 25/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 8.3140e-05 - val_accuracy: 1.0000 - val_loss: 4.2814e-05
Epoch 26/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 4.0711e-05 - val_accuracy: 1.0000 - val_loss: 3.2639e-05
Epoch 27/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 2.7023e-05 - val_accuracy: 1.0000 - val_loss: 3.1582e-05
Epoch 28/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 2.9249e-05 - val_accuracy: 1.0000 - val_loss: 2.2784e-05
Epoch 29/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 2.5088e-05 - val_accuracy: 1.0000 - val_loss: 1.9818e-05
Epoch 30/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 2.2918e-05 - val_accuracy: 1.0000 - val_loss: 2.3426e-05

In [69]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.7552e-05
Test Accuracy: 1.0

In [70]:
y_pred = (model.predict(X_test) > 0.5).astype(int)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [71]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)